# Generated by Django 2.1.1 on 2018-09-26 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlinemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 45, 51, 933301), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='stage_id',
            field=models.IntegerField(choices=[(4, '第一阶段'), (6, '第二阶段'), (14, '第三阶段'), (15, '第一阶段'), (16, '第三阶段')], default=0, verbose_name='阶段id'),
        ),
        migrations.AlterField(
            model_name='outlinemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 11, 45, 51, 933301), verbose_name='更新时间'),
        ),
    ]
