# Generated by Django 2.1.1 on 2018-09-26 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField(choices=[(4, '第一阶段'), (6, '第二阶段'), (14, '第三阶段'), (15, '第一阶段'), (16, '第三阶段')], default=0, verbose_name='阶段id')),
                ('outline_id', models.IntegerField(choices=[(1, '这哪一阶段的'), (5, '基本项目'), (7, 'JDK')], default=0, verbose_name='一级大纲id')),
                ('number', models.IntegerField(default=0, verbose_name='排序')),
                ('sign', models.CharField(max_length=255, verbose_name='标志性内容')),
                ('digest', models.CharField(max_length=255, verbose_name='内容摘要')),
                ('propare', models.CharField(max_length=255, verbose_name='准备工作')),
                ('process', models.CharField(max_length=255, verbose_name='讲课流程')),
                ('attention', models.CharField(max_length=255, verbose_name='准备工作')),
                ('exercise', models.CharField(max_length=255, verbose_name='课后作业')),
                ('share', models.CharField(max_length=255, verbose_name='学生分享')),
                ('management', models.CharField(max_length=255, verbose_name='管理事项')),
                ('remark', models.CharField(max_length=255, null=True, verbose_name='备注')),
                ('status', models.IntegerField(default=0, null=True)),
                ('creater', models.IntegerField(default=0, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 15, 55, 4, 244721), verbose_name='创建时间')),
                ('updater', models.IntegerField(default=0, verbose_name='更新者')),
                ('update_time', models.DateTimeField(default=datetime.datetime(2018, 9, 26, 15, 55, 4, 244721), verbose_name='更新时间')),
            ],
        ),
    ]
