# Generated by Django 2.1.1 on 2018-09-26 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 10, 57, 48, 805221), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='subject_id',
            field=models.IntegerField(choices=[(1, 'JAVA'), (2, 'UI'), (3, 'Python ')], default=0, verbose_name='学科id'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 10, 57, 48, 805221), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='updater',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 10, 57, 48, 805221), verbose_name='更新者'),
        ),
    ]
