# Generated by Django 2.1.1 on 2018-09-27 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0007_auto_20180926_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagemodel',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 11, 11, 16, 802783), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='subject_id',
            field=models.IntegerField(default=0, verbose_name='学科id'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 11, 11, 16, 802783), verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stagemodel',
            name='updater',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 11, 11, 16, 802783), verbose_name='更新者'),
        ),
    ]
